name: flutter_mvu
description: A minimal Elm‑inspired Model‑View‑Update state management library for Flutter.
version: 1.0.3
homepage: https://github.com/MoritzKopmann/flutter_mvu
repository: https://github.com/MoritzKopmann/flutter_mvu
documentation: https://pub.dev/documentation/flutter_mvu/latest/

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0